// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3UjelFehwN51mSPOexKSW9uw45798VI',
    appId: '1:72962647242:web:46ac8d9e587551badf8033',
    messagingSenderId: '72962647242',
    projectId: 'attendanceappfornotifications',
    authDomain: 'attendanceappfornotifications.firebaseapp.com',
    storageBucket: 'attendanceappfornotifications.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4EsEg4HmsiQTbLwAbS1miYSiZYPMziL8',
    appId: '1:72962647242:android:1c6bc88e7c7f474bdf8033',
    messagingSenderId: '72962647242',
    projectId: 'attendanceappfornotifications',
    storageBucket: 'attendanceappfornotifications.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP3UjelFehwN51mSPOexKSW9uw45798VI',
    appId: '1:72962647242:web:01a8c29c771c942bdf8033',
    messagingSenderId: '72962647242',
    projectId: 'attendanceappfornotifications',
    authDomain: 'attendanceappfornotifications.firebaseapp.com',
    storageBucket: 'attendanceappfornotifications.firebasestorage.app',
  );
}
